### ISSUE TITLE
@prisma/client module not found in production mode on Vercel

### ISSUE THREAD

**Issue by nadecancode** [graphql-nexus/nexus-prisma#189]
#### Screenshot
![image](https://user-images.githubusercontent.com/20222292/152629408-d086256d-46ec-4949-9e53-94395fc595dc.png)

#### Description 
This shows up whenever I attempt to query GraphQL in my production/preview build on Vercel (local development works perfectly fine). In addition, I tried ``next build`` and ``next start`` to simulate a production build locally and it worked fine as well.

I am using ``pnpm`` as my package manager and ``turborepo`` for monorepo but I am not sure if it matters.

#### Repro Steps/Link 
Use Next.js on Vercel
Setup Prisma & nexus-prisma
Publish the production build on Vercel

**Comment by abs0lom** [comment]
same issue for me when dockerize an app with `pnpm`... is an `pnpm` issue ! `pnpm` link `node_modules` with an absolute path... I have fallback to `yarn` for fix the issues :disappointed:

**Comment by zkochan** [comment]
pnpm like npm, doesn't install devDependencies, when NODE_ENV is set to production.

Looks like it is not the case with Yarn.

**Comment by garth** [comment]
I had exactly the same issue when building for docker deployments. It seems to be that the build outputs full paths into the generated code instead of relative. So when you move the files to a new location (production host) they paths are wrong.

The only way to fix (beside fixing the underlining issue) is to rebuild generated code on the target environment which may  or may not be possible in all environments.

**Comment by AhmedElywa** [comment]
> same issue for me when dockerize an app with `pnpm`... is an `pnpm` issue ! `pnpm` link `node_modules` with an absolute path... I have fallback to `yarn` for fix the issues 😞

As @abs0lom said it's a `pnpm` issue.

you have two solutions:-

1- Use `npm` or `yarn`.

2- Using `pnpm` with a custom output path you will need to create a configuration file in one of the following locations

→ nexus-prisma.ts
→ nexusPrisma.ts
→ nexus_prisma.ts
→ prisma/nexus-prisma.ts
→ prisma/nexusPrisma.ts
→ prisma/nexus_prisma.ts

Then add the following code:

```js
settings({
  output: './generated/nexus-prisma'
})
```

Because the output will be in `.js` you will need to include the `.js` files into your `tsconfig.ts` file by adding this prop.

```js
{
  "compilerOptions": {
    ...
    "allowJs": true
  },
}
```
